### ISSUE TITLE
Assignment 1 is ready for grading

### ISSUE THREAD

**Issue by anazhibaj** [VIS-2129-F2020/anazhibaj-vis#1]
Hello!
Herein lieth Assignment 1, ready for grading: 
Rmd file link: https://github.com/VIS-2129-F2020/anazhibaj-vis/blob/master/Assignment%201.Rmd
Html file link: https://github.com/VIS-2129-F2020/anazhibaj-vis/blob/master/Assignment-1.html
Looking forward to your feedback!

**Comment by bauranov** [comment]
Overall, great work! Here are some comments on how to make it better.

- Line 1: Add a space between # and text to get a header. The comment applies to all headers. 
- Line 47: Replace {r} with {r, message = FALSE} to suppress unnecessary messages in HTML.
- Heat map: Maybe it would make sense to remove the grey background since it might be mistaken for a plot value.
- It's always a good practice to add labels to the legend, instead of leaving variable names. For example, in the violin plot you can change with scale_fill_discrete(name = "Majority Race", labels = c("Asian", "White", "None")).
- Line 294: Hit Enter to avoid pesky formatting in HTML.

Rock on!
