### ISSUE TITLE
Assignment 2 ready to be graded

### ISSUE THREAD

**Issue by anazhibaj** [VIS-2129-F2020/anazhibaj-vis#2]
Hi! Assignment 2 is ready to be graded. 

Here are the links:
Rmd: https://github.com/VIS-2129-F2020/anazhibaj-vis/blob/master/200923_Assignment_2.Rmd
Html: https://github.com/VIS-2129-F2020/anazhibaj-vis/blob/master/200923_Assignment_2.html

Thank you and enjoy! I hope I attached the right links

**Comment by bauranov** [comment]
Almost the right link :) It's this one: https://vis-2129-f2020.github.io/anazhibaj-vis/filename, and instead of *filename*, add the name of your assignment "200923_Assignment_2", so https://vis-2129-f2020.github.io/anazhibaj-vis/200923_Assignment_2.

Overall, good work. 
- Plotting coordinate system might not be needed, it doesn't add any information, only clutters the plot. 
- Make sure to add a name to the legends and not use the default variable name (gdp_md_est). You can do that with guides(fill=guide_legend(title="New Legend Title"). 
- Use labels and breaks to create a scale for the numbers in the legend.
